/**
 * @constant
 */
const App_Props = {
    COMBOBOX_1: "combobox1",
    COMBOBOX_2: "combobox2",
    COMBOBOX_3: "combobox3",
    PUSH_BUTTON_1: "pushButton1",
    PUSH_BUTTON_2: "pushButton2",
    PUSH_BUTTON_3: "pushButton3",
    PUSH_BUTTON_4: "pushButton4",
    PUSH_BUTTON_5: "pushButton5",
    TOGGLE_BUTTON_1: "toggleButton1",
    TOGGLE_BUTTON_2: "toggleButton2",
    TOGGLE_BUTTON_3: "toggleButton3",
    TOGGLE_BUTTON_4: "toggleButton4",
    TOGGLE_BUTTON_GROUP_1_ITEM_1: "toggleButtonGroup1Item1",
    TOGGLE_BUTTON_GROUP_1_ITEM_2: "toggleButtonGroup1Item2",
    TOGGLE_BUTTON_GROUP_1_ITEM_3: "toggleButtonGroup1Item3",
    TOGGLE_BUTTON_GROUP_1_ITEM_4: "toggleButtonGroup1Item4",
    TOGGLE_RADIO_GROUP_1: "toggleRadioGroup1",
    TOGGLE_RADIO_GROUP_2: "toggleRadioGroup2",
    TOGGLE_RADIO_GROUP_3: "toggleRadioGroup3",
    TOGGLE_RADIO_GROUP_4: "toggleRadioGroup4",
    CHECKBOX_1: "checkbox1",
    CHECKBOX_2: "checkbox2",
    CHECKBOX_3: "checkbox3",
    CHECKBOX_4: "checkbox4",
    CHECKBOX_5: "checkbox5",
    CHECKBOX_6: "checkbox6",
    RADIO_1: "radio1",
    RADIO_2: "radio2",
    RADIO_3: "radio3",
    TEXT_FIELD_1: "textField1",
    TEXT_FIELD_2: "textField2",
    TEXT_FIELD_3: "textField3",
    NUMBER_FIELD_1: "numberField1",
    NUMBER_FIELD_2: "numberField2",
    TIME_FIELD_1: "timeField1",
    TIME_FIELD_2: "timeField2"
};
export default App_Props;